### ISSUE TITLE
Modeline height issue 

### ISSUE THREAD

**Issue by toshism** [mclear-tools/bespoke-modeline#1]
Hey, great theme and modeline. I'm seeing a small issue with the modeline height for buffers visiting files in a git repo. The height of the modeline for the git controlled file ends up being a fair bit taller. I'm guessing it could possibly be font related, maybe due to one of the characters used in the git status section? 

Linux, Emacs == 27.1, font == SF Mono.

Here is a screen shot to illustrate. Sorry, it's kind of big. Also all of my theme/modeline settings are on the right side.
![image](https://user-images.githubusercontent.com/71871/146691397-c1aa2cd3-214f-43f1-b440-b7d87818b38b.png)

Thanks!

**Comment by mclearc** [comment]
Thanks for the bug report! I just made the vc-symbol customizable (EDIT: please pull the latest from main). So you can `(setq  bespoke-modeline-vc-symbol "SYMBOL")` and see if that makes a difference. I also set `(set-fontset-font t 'unicode "Symbola" nil 'prepend)` (note that this presumes [Symbola Font](https://fontlibrary.org/en/font/symbola) is installed) in my .emacs, which allows for better display of unicode. If neither of these work we can try a few other things, but I'm not seeing this in my config so it might also end up being due to some sort of conflict or font problem with your system. Let me know how things go!

**Comment by toshism** [comment]
Looks like it was indeed a font issue. Installing Symbola did not seem to have any affect, but changing the symbol to an ascii character did fix it. 

Thanks!

**Comment by mclearc** [comment]
Closed via https://github.com/mclear-tools/bespoke-modeline/commit/38034550c326c1285f27858cb4d415e5cac59069
