### ISSUE TITLE
How to customize the mode-line to show the org-clock and other info of interest

### ISSUE THREAD

**Issue by proudot** [mclear-tools/bespoke-modeline#2]
Thanks for nice theme, I find it is a simpler while richer alternative to NANO theme. My question is in the title: How to customize the mode-line to show the org-clock and other info of interest ?

**Comment by mclearc** [comment]
Thanks! Org-clock display was broken but it should be fixed via 9699bed298987d3793cc502483dfde6db22a3d66.

The mode-line is very hackable, but I'm also happy to add options if I can figure out how to display them :)

**Comment by proudot** [comment]
Thx! I tried a lil' `straight-pull-package` for both bespole-modeline and bespoke theme, restarted emacs but the clock does not appear. Am I missing something?

**Comment by mclearc** [comment]
Hmmm -- here's what it looks like for me. Note that this only displays when you've clocked in to an org file.
<img width="744" alt="Screen Shot 2022-02-03 at 09 47 29" src="https://user-images.githubusercontent.com/1502422/152366250-a07b6795-f0cd-4d53-a1db-d34a968abc6a.png">

**Comment by mclearc** [comment]
FYI: I pushed another commit (151811abf7faed1be724f8281312506b9dc4cfc6) that fixes display after you clock out.

**Comment by proudot** [comment]
It works now ! The issue was related to straight.el, I am a new to it and though straight-package-pull was enough to update. Thanks! BTW, any good ressource to know how to customize the modeline further ? Cheers!

**Comment by mclearc** [comment]
Good - glad it works now! In terms of customizing, it really depends on what you want to display. I have kept things relatively minimal on purpose, both because I want to reduce clutter and because it means less overhead for maintaining the code ;) But if you're thinking of hacking away the place to start with the code is looking at the [`bespoke-default-mode`](https://github.com/mclear-tools/bespoke-modeline/blob/2b6a871f68c1596f4c2df0854f5edb366af4ba8b/bespoke-modeline.el#L497) function. Most other display functions in the modeline are running off of that (or some modification of it). And the function [`bespoke-modeline`](https://github.com/mclear-tools/bespoke-modeline/blob/2b6a871f68c1596f4c2df0854f5edb366af4ba8b/bespoke-modeline.el#L952) is where all the functions for display end up going. 

If you just want to read more about how the mode-line function in emacs work generically here are some links: 

-   [List of variables with
    descriptions](http://doc.endlessparentheses.com/Var/mode-line-format.html)
-   [Amit\'s custom mode line (nice
    walkthrough)](https://amitp.blogspot.com/2011/08/emacs-custom-mode-line.html)
-   [More customization from
    Amit](https://amitp.blogspot.com/2019/07/emacs-mode-line-simplified.html)
- [customization walk-through](https://blog.tygr.info/emacs/mode-line.html)

And like I said -- if you have specific requests I can see whether I can add them. Or you can always open a PR ;)

**Comment by proudot** [comment]
Thanks a lot for the input, I will tinker around when I get the chance :).
